title: Welcome New Github Page
author: Newbie
email: hahaha123_456@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 
  Train github
  
# social links
twitter_username: tuananhat # DO NOT include the @ character, or else the build will fail!
github_username:  tuananhat # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
